//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarProp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int Id_Transacción { get; set; }
        public Nullable<int> Vehiculo { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Tiene_Ralladuras { get; set; }
        public string Cantidad_Conbustible { get; set; }
        public string TieneGomaRepuesto { get; set; }
        public string TieneGato { get; set; }
        public string TieneRoturaCrsital { get; set; }
        public string EstadoGomas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Empleado_inspeccion { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
