//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarProp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int Id_Modelo { get; set; }
        public Nullable<int> Id_Marca { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
