//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarProp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> Id_empleado { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
