//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarProp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuRole
    {
        public int Id_Role { get; set; }
        public string Descripcion { get; set; }
    }
}
